### ISSUE TITLE
TimeStamp for PyData MMM

### ISSUE THREAD

**Issue by Muthukamalan** [takechanman1228/mmm_pydata_global_2022#1]
youtube link: https://www.youtube.com/watch?v=u4U_PUTasPQ

0:17 Agenda
1:01 About Hajime Takeda
2:14 Expected takeaway
2:36 Whatis MMM
4:44 Key Challenges in Media Optimization
6:33 Three Important Challenges
7:39 Steps to do MMM
8:00 Data Preparation
11:39 Modeling
14:30 Shape effect is modeled by Hill Function
15:10 Carry over effect is modeled by Adstock
16:17 Model Proposed by Google Researchers Jin et al
17:16 Demo with LightweightMMM
18:45 LightweightMMM Flowchart
19:13 Demo
25:21 Outcome
26:43 Summary
27:16 Improve Model's accuracy
28:54 Conclusion

Hope it'll be helpful

**Comment by takechanman1228** [comment]
@Muthukamalan Thank you very much for your comment!
