### ISSUE TITLE
will it work on windows 11?

### ISSUE THREAD

**Issue by Sandy4321** [takechanman1228/mmm_pydata_global_2022#2]
will it work on windows 11?
installation for lightweight_mmm fails 
![image](https://user-images.githubusercontent.com/11426119/232155432-f5a04f0f-ff37-45f9-a112-fefd7c3e2fa7.png)

**Comment by takechanman1228** [comment]
@Sandy4321 Thank you for your comment.
I understand that you may be experiencing difficulties with installing the lightweightmm on your Windows 11 system. If this is the case, it might be helpful to seek assistance from the official lightweightmm repositoryby raising your issue.
https://github.com/google/lightweight_mmm

I hope this works.
